spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
server:
  port: 8000